config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats, except: [:index]

  get '/search', to: 'flats#index'
  root to: 'flats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :number_of_guests, :price_per_night, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  def index
    @flats = params[:query] ? Flat.where("name LIKE '%#{params[:query]}%'") : Flat.all
  end

  def show; end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      # redirect_to flat_path(@flat)
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to root_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :picture_url %>
    <%= f.input :description %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary mt-4" %>
    <%= link_to "Cancel", :back, {:class=>"btn btn-danger mt-4"} %>
  </div>
<% end %>

app/views/flats/_form_search.html.erb
<%= form_with url: "search", method: :get, class: "d-flex" do |f| %>
  <%= f.text_field :query, class: "form-control mx-2" %>
  <%= f.submit "Search", class: "btn btn-outline-success" %>
<% end %>

app/views/flats/edit.html.erb
<div class="container mt-4">
  <div class="flat-form">
    <h1>Edit flat <%= @flat.name %></h1>
    <%= render 'form', flat: @flat %>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container my-3">
  <h2>All our Flats (<%= @flats.size %>)</h2>
  <div class="cards row">
    <% @flats.each do |flat| %>
      <div class="col-4">
        <div class="flat-card">
            <div class="flat-card-image" style="background-image: url( <%= flat.picture_url %> )"></div>
            <div class="flat-card-content">
              <div class="flat-card-title">
                <h4><%= flat.name %></h4>
              </div>
              <p><%= flat.description %></p>
              <div class="d-flex">
                <i class="material-icons me-2">people</i><span><%= flat.number_of_guests %></span>
                <i class="material-icons ms-3 me-2">euro_symbol</i><%= flat.price_per_night %>
              </div>
            </div>
            <div class="flat-card-actions">
              <%= link_to 'More info', '#' %>
              <%= link_to 'Edit', '#', class: "mx-3 text-warning" %>
              <%= link_to 'Remove', '#',  method: :delete, data: { confirm: 'Are you sure?' }, class: "ml-3 text-danger" %>
            </div>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-5">
  <div class="flat-form">
    <h2>Add a new flat</h2>
    <%= render 'form', flat: @flat %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url( <%= @flat.picture_url %> );">
</div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1> <%= @flat.name %> </h1>
        <p> <%= @flat.address %> </p>
      </div>
      <div class="flat-show-card">
        <h3> A bit more about this flat... </h3>
        <p> <%= @flat.description %> </p>
        <%# <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=10 Clifton Gardens London W9 1DT&amp;zoom=13&amp;scale=2&amp;size=1000x1000&amp;maptype=roadmap&amp;markers=color:red%7C10 Clifton Gardens London W9 1DT&amp;key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY')"></div> %>
        <iframe
          src='https://api.mapbox.com/styles/v1/mapbox/streets-v11.html?title=true&zoomwheel=false&access_token=pk.eyJ1IjoiaWdvcmRlcG9sbGkiLCJhIjoiY2tqcmVobWlpMHhlbTJ6cDVhZWU0eG1pOSJ9.J2jrqkEJO-cILajQb4aAtg#15/37.771/-122.436' width='100%' height='400px' title='Mapbox Styles embed'>
        </iframe>
      </div>
    </div>
    <div class="col-4">
      <div class="flat-show-card">
        <h5> Book this place! </h5>
        <form action="">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Check-in date" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <input type="text" class="form-control" placeholder="Check-out date" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="d-flex">
          <i class="material-icons me-2">people</i><span><%= @flat.number_of_guests %></span>
          <i class="material-icons ms-3 me-2">euro_symbol</i><%= @flat.price_per_night %>
        </div>
      </div>
      <div class="flat-show-card d-flex justify-content-between align-items-center">
        <h6>Share</h6>
        <div class="flex">
            <i class="fa fa-envelope-square fa-2x"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
      <%= link_to "Simple Airbnb", root_path, class: "navbar-brand mx-3" %>
      <div class="navbar-actions d-flex">
        <%= render 'form_search', flat: @flat %>
        <%= link_to "Add flat", new_flat_path, class: "btn btn-outline-primary mx-2" %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>